dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
env:
  - DJANGO_SETTINGS_MODULE='bloggable.setting'
  - SECRET_KEY='v)xmimh@!*)^ht5)_+]\z8!wdi86h_ps%f9&mjbh!258^bd/'
install:
  - pip install -r requirements.txt
script:
  - python manage.py test