# Generated by Django 2.1.5 on 2019-01-31 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20190131_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_clap',
            field=models.ManyToManyField(blank=True, related_name='posts_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
